## Our Projects! {-}

<div>
<span style = "float: right;">**Abigail Graham**<br></span><a href = "https://sway.office.com/wieQriZFOf2Mggzy?ref=Link" target = "_blank">Investigating Passive and Active Social Media Use as a Predictor for Student Loneliness</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Afrah_Fathima**<br></span><a href = "https://sway.office.com/c7iAyr2mmymrhiJa?ref=Link" target = "_blank">Online Self-Perception and other factors Affecting Instagram Users’ Mental Health.</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Alicja Turek**<br></span><a href = "https://sway.office.com/IblaX5UXYsAjxOSP?ref=Link" target = "_blank">Mixed Method Approach Investigating the Effect of a Virtual Reality Setting on the ASMR Experience.</a>
</div>


<div>
<br>
</div>



---

<div>
<span style = "float: right;">**Ashley Smellie**<br></span><a href = "https://sway.office.com/bwxCyoUAOeh04Vil?ref=Link&loc=play" target = "_blank">What Determines Individual Differences in Climate Change Belief?</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Alison Lloyd**<br></span><a href = "https://sway.office.com/rOlOFY5S7TtAjb21?ref=Link" target = "_blank">A qualitative exploartion into the experience of people living with epilepsy and mental illness.</a>
</div>

<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Matt Ogden**<br></span><a href = "https://youtu.be/kipEOmqQDZ0" target = "_blank">Mental Health of Students Impacted by the Cost of Living Crisis in 2022.</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Amalia Ikonomidis**<br></span><a href = "https://sway.office.com/WUygjnZheD5Zojt5?ref=Link" target = "_blank">How Living the Dream Might Be a Nightmare: The Role of Poor 
Quality of Sleep in Lucid Dreaming and Nightmare Frequency.</a>
</div>

<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Annie Reid**<br></span><a href = "https://sway.office.com/YBwXoPPfEAFMplm9?ref=Link" target = "_blank">Chronic Illness and Psychological Distress: The Role of Social Deprivation.</a>
</div>

<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Aoife McCourt**<br></span><a href = "https://sway.office.com/scHY0YY0JaOaIVzR?ref=Link"target = "_blank">Breaking Barriers: Exploring the Attitudes and
Perceptions Towards Integration Between Protestant and Catholic Communities in Post-Conflict Northern Ireland.</a>
</div>

<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Caitlin McDonald**<br></span><a href = "https://sway.office.com/I3ZUOlMwTHARkQVJ?ref=Link"target = "_blank">Exploring perspectives of first year undergraduate students on the use of social media as a tool to support anxiety and worry</a>
</div>

<div>
<br>
</div>

---


<div>
<span style = "float: right;">**Cameron Oyston**<br></span><a href = "https://sway.office.com/hcEVxQ7g0GYwSRXP?ref=Link"target = "_blank">On the Reaffirmation of the Relationship Between the ODI and the DASS</a>
</div>

<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Charlotte Schneider**<br></span><a href = "https://sway.office.com/fJ0vGXXEGRtH7eby?ref=Link"target = "_blank">Interactive Effects of Job Advertisement Wording, Applicants’ Gender and Work Experience on Perceived Candidate Suitability in an Experimental Vignette Study</a>
</div>

<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Ciara Wilson**<br></span><a href = "https://sway.office.com/fJ0vGXXEGRtH7eby?ref=Link"target = "_blank">A comparison of factors influencing conviction outcomes between Scotland and England's jury systems.</a>
</div>

<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Claire Crease**<br></span><a href = "https://sway.office.com/6gn7MIdY6PoIUHmS?ref=Link"target = "_blank">An Investigation of the Impact of Parental Academic Success on the Experience of Impostor Phenomenon.</a>
</div>

<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Daniel Moore**<br></span><a href = "https://sway.office.com/2Lpga6zmZ7ctd9tB?ref=Link&loc=play"target = "_blank">Are you ready for work?</a>
</div>

<div>
<br>
</div>

---


<div>
<span style = "float: right;">**Gabbie Franjeskou**<br></span><a href = "https://sway.office.com/GZSUnkI9dHyPwiga?ref=Link"target = "_blank">Investigating bilingual's perception of climate change messages.</a>
</div>

<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Gillian Seawright**<br></span><a href = "https://sway.office.com/Xr1lECH0iEnRfi7W?ref=Link"target = "_blank">The impact of parenting styles on students' mental health and self-esteem.</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Hamish Barrett**<br></span><a href = "https://sway.office.com/Xr1lECH0iEnRfi7W?ref=Link"target = "_blank">How absolute poverty and perception of one's own poverty predict students' wellbeing and sense of belonging</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Hannah Luke**<br></span><a href = "https://sway.office.com/Xr1lECH0iEnRfi7W?ref=Link"target = "_blank">Hydration motivation and the role of amateur sport.</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Holli Ella**<br></span><a href = "https://sway.office.com/LKoPdxDtCV7QCBPW?ref=Link&loc=play"target = "_blank">The Effect of Instagram's "Fitspiration" Culture on Body Image Among Men.</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Jai Potter**<br></span><a href = "https://sway.office.com/KtGpcDTRiC4S29Cd?ref=Link"target = "_blank">The experience of Imposter Syndrome in First-Generation University Honours students and the impact of the COVID-19 pandemic.</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Jemma Gough**<br></span><a href = "https://sway.office.com/Rt49GU6mvLiPRPoF?ref=Link"target = "_blank">Investigating Whether Dimensions of Religiosity and Perfectionism are  Predictive of Mental Wellbeing in a UK Christian Sample.</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Jenna Jones**<br></span><a href = "https://sway.office.com/Rt49GU6mvLiPRPoF?ref=Link"target = "_blank">An Investigation in the Potential Association between Perceived Parental Support, Mental Health, and Academic Success in Undergraduates</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Jordyn Marais**<br></span><a href = "https://sway.office.com/tu2xlV4FlXtva2CD?ref=Link"target = "_blank">Conceptualisations and Practices of Good Mental
Health in South Africa.</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Julia Love**<br></span><a href = "https://sway.office.com/XdkBWQg0jtnD8U8F?ref=Link"target = "_blank">Mindfulness Apps For Student Wellbeing.</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Julie Garroway**<br></span><a href = "https://sway.office.com/OnaFfYPB1hdVUBKA?ref=Link"target = "_blank">Agreeableness and Religiosity as Predictors of Disgust Sensitivity.</a>
</div>


<div>
<br>
</div>

---

<div>
<span style = "float: right;">**Juliet Cameron**<br></span><a href = "https://sway.office.com/mUJzQiwaN1dqdyE6?ref=Link"target = "_blank">The Sad Playlist: Investigating the Motivations and Benefits of Listening to Sad Music.</a>
</div>


<div>
<br>
</div>